name: Publish Fork

on:
  push:
    branches: ['build/*']
  pull_request:
    branches: ['build/*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Static Checks
        run: ./gradlew check

  deploy:
    name: Publish Fork
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [ static_checks ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish library
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryUsername: ${{ secrets.JFROG_USERNAME }}
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryPassword: ${{ secrets.JFROG_PASSWORD }}
